### ISSUE TITLE
[otel-arrow-rust] Build Cache for CICD

### ISSUE THREAD

**Issue by daviddahl** [open-telemetry/otel-arrow#380]
- Implement CICD build cache to speed up CI job stages

I am curious what any interested folks think the best solution for caching builds in CI might be in 2025?

**Comment by gouslu** [comment]
I can work on this.

**Comment by gouslu** [comment]
[I added cache to the rust build portion of bench job](https://github.com/open-telemetry/otel-arrow/pull/690/files), which sped up the build portion, but bench still runs and runs long. I was wondering if you'd agree to add a logic like this to not run bench when there are no changes in rust/** folder.

``` yaml
  changes:
    runs-on: ubuntu-latest
    outputs:
      bench: ${{ steps.filter.outputs.bench }}
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: dorny/paths-filter@de90cc6fb38fc0963ad72b210f1f284cd68cea36 # v3.0.2
        id: filter
        with:
          filters: |
            bench:
              - 'rust/**'
```
