### ISSUE TITLE
[otap-dataflow] signal generator receiver

### ISSUE THREAD

**Issue by c1ly** [open-telemetry/otel-arrow#673]
Receiver that will generate otlp signals (for otap we call the encoding method to go from otlp -> otap) based on a given configuration. this receiver will be used to help test pipelines and pipeline components

**Comment by lquerel** [comment]
Receiver name: `FakeDataGenerator`

In the configuration, we should be able for each signal type to specify scenarios:
- Number of batches + delay between each batch
- For each batch, number of signals
- For metric signals
   - Instrument
   - Number of data points
   - Number of attributes
- For log signals
   - Number of attributes
- For spans
   - Number of attributes
   - Number of events
   - Number of links
- For Profiles
   - TBD

```yaml
name: <scenario_name>
steps:
  - name: <step_name>
     type: signal | control
     signal_type: metric|log|span|profile
     batch_count: <number>
     delay_between_batch: <duration>
     metrics:
        attribute_count: <number>
        ...
     logs:
       ...
  - name: <another_step>
     ...     
```

Fetch goals:
- Support distributions
